import Head from "next/head";
import { useState } from "react";
import Container from "../components/Container";

export default function Home() {
  const [theme,setTheme] = useState("Dark")
  return (
    <div className={`${theme==="Dark"?"bg-Dark-main text-white":theme==="Light"?"bg-Light-main text-white":theme==="Violette"?"bg-Violette-main text-white":""} w-screen h-screen flex justify-center items-center`}>
      <Head>
        <title>Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container theme={theme} setTheme={setTheme}/>
    </div>
  );
}
